apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-backend.fullname" . }}-config
  labels:
    {{- include "demo-backend.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Values.config.yaml | nindent 4 }}
