apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "o2-dms-adapter.fullname" . }}
  labels:
    {{- include "o2-dms-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "o2-dms-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "o2-dms-adapter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "o2-dms-adapter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: o2-dms-adapter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-addr=:8088"
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.auth.bearerToken }}
          env:
            - name: O2DMS_BEARER_TOKEN
              value: {{ .Values.auth.bearerToken | quote }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
