{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "o2-dms-adapter.serviceAccountName" . }}
  labels:
    {{- include "o2-dms-adapter.labels" . | nindent 4 }}
{{- end }}
