#!/usr/bin/env bash
# Phase 8 P8-T-103 — kind smoke installer for the busy-idle 垂直伸缩
# substrate (ADR-0012 + P8-T-005 NPUVerticalScaler CRD + P8-T-006 metrics
# ingestor + P8-T-007 controller + P8-T-008 AllocateBundle wiring).
#
# Run AFTER tests/e2e/kind/phase7/install.sh so the cluster has:
#   * Phase 4-7 ResourceSlices + cert-manager + inference-operator +
#     scheduler-plugin + NPUSliceTemplate substrate
#   * Phase 7 P7-T-007 NPUSliceTemplate CRD installed (via npu-dra-driver
#     chart bundle)
#   * Phase 8 P8-T-005 NPUVerticalScaler CRD installed (via inference-
#     operator chart bundle · phase 8 helm upgrade triggered by chart
#     update)
#   * Phase 8 P8-T-007 NPUVerticalScalerReconciler running in the
#     inference-operator deployment (registered at cmd/main.go startup
#     when chart `metrics.prometheusURL` empty → degraded mode · ingestor
#     returns NoData=true)
#
# Phase 8 layering:
#   1. Apply qwen-pd-busy + qwen-pd-idle NPUSliceTemplates → wait for
#      Validated=True + Allocatable=True per Phase 7 template_controller
#   2. Apply qwen-pd ModelService (pre-seeded annotation
#      npu.huawei.com/slice-template=qwen-pd-idle to demo the carry-
#      forward annotation→Pod-label propagation gap)
#   3. Apply qwen-pd-scaler NPUVerticalScaler → wait for ConditionActive
#   4. (P8-T-008 wiring demo workaround) Stamp the same annotation onto
#      the ResourceClaim(s) generated by the ModelService — kind smoke
#      proves T008 claim_controller bundle path dispatches correctly
#      without waiting for the carry-forward propagation chain
#
# Bails on first failure with kubectl describe / logs dump.

set -euo pipefail

KIND_CLUSTER="${KIND_CLUSTER:-ocloud-e2e}"
NS_INF="${NS_INF:-ocloud-system}"
NS_DRA="${NS_DRA:-ocloud-system}"
WAIT_NST_SECONDS="${WAIT_NST_SECONDS:-30}"
WAIT_NVS_SECONDS="${WAIT_NVS_SECONDS:-60}"
WAIT_DEPLOY_SECONDS="${WAIT_DEPLOY_SECONDS:-90}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIX_NST_BUSY="${SCRIPT_DIR}/fixtures/npuslicetemplate-qwen-pd-busy.yaml"
FIX_NST_IDLE="${SCRIPT_DIR}/fixtures/npuslicetemplate-qwen-pd-idle.yaml"
FIX_MS="${SCRIPT_DIR}/fixtures/modelservice-qwen-pd.yaml"
FIX_NVS="${SCRIPT_DIR}/fixtures/npuverticalscaler-qwen.yaml"

cmd_apply_templates() {
  echo "== Phase 8 T103-1: apply qwen-pd-busy + qwen-pd-idle NPUSliceTemplates =="
  kubectl apply -f "${FIX_NST_BUSY}"
  kubectl apply -f "${FIX_NST_IDLE}"

  for tpl in qwen-pd-busy qwen-pd-idle; do
    echo "== wait for ${tpl} Validated=True (timeout ${WAIT_NST_SECONDS}s) =="
    if ! kubectl wait --for=jsonpath='{.status.conditions[?(@.type=="Validated")].status}'=True \
        --timeout="${WAIT_NST_SECONDS}s" \
        npust "${tpl}"; then
      echo "::warning::NPUSliceTemplate ${tpl} not Validated within ${WAIT_NST_SECONDS}s"
      kubectl describe npust "${tpl}" || true
    fi
  done
}

cmd_apply_modelservice() {
  echo "== Phase 8 T103-2: apply qwen-pd ModelService (annotation-seeded) =="
  kubectl -n "${NS_INF}" apply -f "${FIX_MS}"
  echo "== wait for ModelService to enter Provisioning (best-effort) =="
  if ! kubectl -n "${NS_INF}" wait \
      --for=jsonpath='{.status.phase}'=Provisioning \
      --timeout="${WAIT_DEPLOY_SECONDS}s" \
      modelservice/qwen-pd 2>/dev/null; then
    echo "::warning::ModelService qwen-pd not in Provisioning within ${WAIT_DEPLOY_SECONDS}s — describing"
    kubectl -n "${NS_INF}" describe modelservice qwen-pd || true
    # Don't fail; assert.sh covers strict checks.
  fi
}

cmd_apply_scaler() {
  echo "== Phase 8 T103-3: apply NPUVerticalScaler =="
  kubectl -n "${NS_INF}" apply -f "${FIX_NVS}"

  # The scaler runs its Reconcile loop ~30s after creation (degraded
  # mode requeueAfter=30s). Wait for at least one ConditionActive entry
  # to confirm the Reconciler observed the object.
  echo "== wait for NPUVerticalScaler ConditionActive (any status · timeout ${WAIT_NVS_SECONDS}s) =="
  local deadline=$((SECONDS + WAIT_NVS_SECONDS))
  while [[ ${SECONDS} -lt ${deadline} ]]; do
    if kubectl -n "${NS_INF}" get npuvs qwen-pd-scaler \
        -o jsonpath='{.status.conditions[?(@.type=="Active")].status}' 2>/dev/null \
        | grep -qE '(True|False)'; then
      echo "  OK · ConditionActive observed"
      return 0
    fi
    sleep 5
  done
  echo "::warning::NPUVerticalScaler ConditionActive not stamped within ${WAIT_NVS_SECONDS}s — describing"
  kubectl -n "${NS_INF}" describe npuvs qwen-pd-scaler || true
}

# cmd_demo_bundle_path removed in P9-T-004 (2026-05-21).
#
# Phase 8 used a direct `kubectl annotate resourceclaim` workaround to stamp
# the slice-template annotation onto ResourceClaims because the propagation
# chain (NPUVerticalScaler → ModelService annotation → deployment_builder →
# Pod label → claim_controller bundle path) was incomplete: deployment_builder
# did NOT propagate ms.Annotations[npu.huawei.com/slice-template] to the Pod
# template label.
#
# P9-T-004 closes this gap — deployment_builder.go::buildDeployment now reads
# ms.Annotations[SliceTemplateAnnotation] and propagates to
# dep.Spec.Template.Labels[SliceTemplateAnnotation] naturally (4 test cases
# in deployment_builder_test.go::TestSliceTemplateLabelPropagation).
#
# The chain is now end-to-end:
#   NPUVerticalScaler.spec.scaleSlice.{busy,idle}TemplateName
#     ↓ NPUVerticalScaler controller patches ModelService.metadata.annotations[npu.huawei.com/slice-template]
#   ModelService.Annotations[npu.huawei.com/slice-template]
#     ↓ deployment_builder (P9-T-004) propagates to Pod template Labels
#   Pod.Spec.Template.Labels[npu.huawei.com/slice-template]
#     ↓ claim_controller (npu-dra-driver · P8-T-008 wiring) reads label
#   claim_controller bundle path resolves NPUSliceTemplate ref → AllocateBundle
#
# No manual `kubectl annotate` step needed for kind smoke; the chain works
# from ModelService apply through controller chain naturally.

cmd_all() {
  cmd_apply_templates
  cmd_apply_modelservice
  cmd_apply_scaler
}

case "${1:-all}" in
  apply-templates)     cmd_apply_templates ;;
  apply-modelservice)  cmd_apply_modelservice ;;
  apply-scaler)        cmd_apply_scaler ;;
  all)                 cmd_all ;;
  *)
    echo "usage: $0 [apply-templates|apply-modelservice|apply-scaler|all]" >&2
    exit 2
    ;;
esac
