apiVersion: v1
kind: Service
metadata:
  name: {{ include "software-mgmt-operator.fullname" . }}
  labels:
    {{- include "software-mgmt-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "software-mgmt-operator.selectorLabels" . | nindent 4 }}
