/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 集群列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cluster"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 集群详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: components["parameters"]["ClusterIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cluster"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{clusterId}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 集群拓扑（节点 + NPU + 切片 + 池）
         * @description 返回完整拓扑图数据。供前端 G6 渲染。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 拓扑深度。slice = 展开到切片 */
                    depth?: "node" | "npu" | "slice";
                };
                header?: never;
                path: {
                    clusterId: components["parameters"]["ClusterIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Topology"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 节点列表 */
        get: {
            parameters: {
                query?: {
                    clusterId?: string;
                    poolName?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 节点详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeName: components["parameters"]["NodeNamePath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeName}/npus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 节点上 NPU 列表（含切片状态） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeName: components["parameters"]["NodeNamePath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NPU"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/npu-slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NPU 切片池列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NPUSlicePool"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/npu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** NPU 池列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NPUPool"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 节点池列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodePool"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pools/cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 集群池列表（多站点联邦） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClusterPool"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作负载列表 */
        get: {
            parameters: {
                query?: {
                    namespace?: string;
                    type?: "inference" | "benchmark" | "training" | "other";
                    status?: "pending" | "running" | "succeeded" | "failed" | "unknown";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workload"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workloads/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作负载详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    namespace: components["parameters"]["NamespacePath"];
                    name: components["parameters"]["NamePath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkloadDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workloads/{namespace}/{name}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作负载日志（流式或分页） */
        get: {
            parameters: {
                query?: {
                    container?: string;
                    tail?: number;
                    since?: string;
                };
                header?: never;
                path: {
                    namespace: components["parameters"]["NamespacePath"];
                    name: components["parameters"]["NamePath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workloads/{namespace}/{name}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作负载业务指标（TTFT、Throughput 等） */
        get: {
            parameters: {
                query?: {
                    window?: "5m" | "15m" | "1h" | "6h" | "24h";
                };
                header?: never;
                path: {
                    namespace: components["parameters"]["NamespacePath"];
                    name: components["parameters"]["NamePath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkloadMetrics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 预置应用列表（来自 ConfigMap） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preset"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets/{presetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 预置应用详情（含完整 manifest） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    presetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresetDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 部署一个应用 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeployRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeployResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 资源冲突（手动指定的资源被占用） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deploy/{deployId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除一个已部署的应用 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deployId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 透传 PromQL 查询（白名单）
         * @description 仅允许白名单内的 PromQL 模板（不允许任意查询，安全考虑）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MetricQueryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricQueryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已注册的查询模板列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricTemplate"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grafana/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 签发带 token 的 Grafana 嵌入 URL */
        get: {
            parameters: {
                query: {
                    dashboard: string;
                    variables?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GrafanaURL"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            datasources?: {
                [key: string]: "ok" | "error" | "disabled";
            };
        };
        Version: {
            /** @example 0.1.0 */
            version?: string;
            commit?: string;
            /** Format: date-time */
            buildTime?: string;
        };
        Error: {
            /** @example NotFound */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ResourceRef: {
            /** @example NPUSlicePool */
            kind: string;
            name: string;
            namespace?: string;
        };
        Cluster: {
            id: string;
            name: string;
            /** @enum {string} */
            role?: "edge-single" | "small-cluster" | "multi-site-member";
            /** @example Site-A */
            location?: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "unreachable";
            kubernetesVersion?: string;
            nodeCount?: number;
            npuCount?: number;
            labels?: {
                [key: string]: string;
            };
            annotations?: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt?: string;
        };
        Topology: {
            nodes: components["schemas"]["TopologyNode"][];
            edges: components["schemas"]["TopologyEdge"][];
            meta?: {
                clusterId?: string;
                /** Format: date-time */
                generatedAt?: string;
            };
        };
        TopologyNode: {
            id: string;
            /** @enum {string} */
            type: "cluster" | "nodepool" | "node" | "npu" | "slice" | "network";
            label: string;
            /** @enum {string} */
            status?: "healthy" | "busy" | "idle" | "degraded" | "failed" | "unknown";
            /**
             * @description type 相关的字段：
             *     - node: cpu, memory, arch, os, numaCount
             *     - npu: model, vram, aiCoreTotal, hccsGroup
             *     - slice: parentNPU, aiCore, vramMB, allocatedTo
             */
            attributes?: {
                [key: string]: unknown;
            };
        };
        TopologyEdge: {
            source: string;
            target: string;
            /** @enum {string} */
            type: "contains" | "hccs" | "network" | "allocated";
            attributes?: {
                [key: string]: unknown;
            };
        };
        Node: {
            name: string;
            clusterId?: string;
            role?: ("control-plane" | "worker" | "edge")[];
            /** @enum {string} */
            status: "Ready" | "NotReady" | "Unknown";
            cpu?: components["schemas"]["Quantity"];
            memory?: components["schemas"]["Quantity"];
            /** @example amd64 */
            arch?: string;
            kernelVersion?: string;
            os?: string;
            kubeletVersion?: string;
            npuCount?: number;
            labels?: {
                [key: string]: string;
            };
        };
        NodeDetail: components["schemas"]["Node"] & {
            numa?: components["schemas"]["NumaNode"][];
            networkInterfaces?: {
                name?: string;
                mac?: string;
                ips?: string[];
                speed?: string;
            }[];
            storage?: {
                device?: string;
                size?: components["schemas"]["Quantity"];
                /** @enum {string} */
                type?: "ssd" | "hdd" | "nvme";
            }[];
            taints?: Record<string, never>[];
        };
        NumaNode: {
            id?: number;
            cpus?: number[];
            memory?: components["schemas"]["Quantity"];
            /** @description 该 NUMA 节点上的 NPU 设备 ID 列表 */
            npus?: string[];
        };
        Quantity: {
            /** @example 16Gi */
            raw: string;
            /** Format: int64 */
            bytes?: number | null;
        };
        NPU: {
            /** @example npu-0 */
            id: string;
            nodeName?: string;
            /** @example Ascend910B */
            model: string;
            index?: number;
            vramMiB?: number;
            aiCoreTotal?: number;
            numaNode?: number;
            /** @example hccs-0 */
            hccsGroup?: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "faulty" | "offline";
            /** @enum {string} */
            sliceMode?: "whole" | "fixed-template" | "dynamic";
            slices?: components["schemas"]["NPUSlice"][];
            usage?: components["schemas"]["NPUUsage"];
        };
        NPUSlice: {
            id: string;
            parentNPU?: string;
            /** @example vir04 */
            template?: string;
            aiCore?: number;
            vramMiB?: number;
            /** @enum {string} */
            status: "available" | "allocated" | "faulty";
            allocatedTo?: {
                namespace?: string;
                podName?: string;
                containerName?: string;
            } | null;
            usage?: components["schemas"]["NPUUsage"];
        };
        NPUUsage: {
            /**
             * Format: float
             * @description 0-100
             */
            aiCoreUtilization?: number;
            /**
             * Format: float
             * @description 0-100
             */
            vramUtilization?: number;
            vramUsedMiB?: number;
            /** Format: float */
            memoryBandwidthUtilization?: number | null;
            /** Format: float */
            temperature?: number | null;
            /** Format: float */
            power?: number | null;
        };
        NPUSlicePool: {
            name: string;
            namespace?: string;
            npuPoolRef?: string;
            /** @enum {string} */
            strategy: "FixedTemplate" | "Dynamic";
            fixedTemplates?: {
                name?: string;
                aiCoreCount?: number;
                memoryMiB?: number;
            }[];
            dynamicSlicing?: {
                minAICore?: number;
                maxAICore?: number;
                memoryGranularityMiB?: number;
                allowAggregation?: boolean;
            } | null;
            status?: {
                totalSlices?: number;
                allocatedSlices?: number;
                availableSlices?: number;
            };
        };
        NPUPool: {
            name: string;
            nodePoolRef?: string;
            npuModel?: string;
            sliceStrategy?: string;
            status?: {
                totalNPUs?: number;
                healthyNPUs?: number;
                allocatedNPUs?: number;
                hccsTopology?: Record<string, never> | null;
            };
        };
        NodePool: {
            name: string;
            clusterPoolRef?: string;
            /** @enum {string} */
            role?: "edge" | "core";
            location?: string;
            selector?: {
                [key: string]: unknown;
            };
            status?: {
                nodes?: string[];
                totalCPU?: components["schemas"]["Quantity"];
                totalMemory?: components["schemas"]["Quantity"];
            };
        };
        ClusterPool: {
            name: string;
            clusters?: {
                clusterId?: string;
                /** @enum {string} */
                syncPolicy?: "Push" | "Pull";
            }[];
            status?: {
                healthyClusters?: string[];
                unhealthyClusters?: string[];
            };
        };
        Workload: {
            name: string;
            namespace: string;
            /** @enum {string} */
            type: "inference" | "benchmark" | "training" | "other";
            /** @example Deployment */
            kind?: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed" | "unknown";
            replicas?: {
                desired?: number;
                ready?: number;
            };
            nodeNames?: string[];
            npuUsage?: {
                allocated?: number;
                slices?: string[];
            };
            /** Format: date-time */
            createdAt?: string;
            labels?: {
                [key: string]: string;
            };
        };
        WorkloadDetail: components["schemas"]["Workload"] & {
            pods?: components["schemas"]["Pod"][];
            /** @description Pod 之间的关系（PD 分离: prefill→decode） */
            relations?: {
                from?: string;
                to?: string;
                /** @enum {string} */
                type?: "pd-pair" | "sidecar" | "init" | "peer";
            }[];
            /** @description 完整 spec（command, args, env 等） */
            spec?: {
                [key: string]: unknown;
            };
        };
        Pod: {
            name?: string;
            namespace?: string;
            nodeName?: string;
            status?: string;
            containers?: {
                name?: string;
                image?: string;
                command?: string[];
                args?: string[];
                resources?: {
                    cpu?: string;
                    memory?: string;
                    npuSlices?: string[];
                };
            }[];
        };
        WorkloadMetrics: {
            throughput?: {
                inputTokensPerSec?: number;
                outputTokensPerSec?: number;
                requestsPerSec?: number;
            };
            latency?: {
                ttftMs?: components["schemas"]["Percentile"];
                itlMs?: components["schemas"]["Percentile"];
                e2eMs?: components["schemas"]["Percentile"];
            };
            resourceUsage?: {
                cpuUtilization?: number;
                memoryUtilization?: number;
                npuUtilization?: number;
                vramUtilization?: number;
            };
            /** Format: date-time */
            sampleAt?: string;
        };
        Percentile: {
            p50?: number;
            p90?: number;
            p99?: number;
        };
        Preset: {
            /** @example qwen-8b-pd */
            id: string;
            /** @example Qwen 8B PD Disaggregated */
            name: string;
            /** @enum {string} */
            kind: "inference" | "benchmark" | "inference-pd";
            /** @example 8B */
            modelSize?: string;
            /** @enum {string} */
            runtime?: "mindie" | "vllm" | "triton";
            requirements?: {
                npuCount?: number;
                npuModel?: string;
                vramMiBPerNPU?: number;
                cpu?: components["schemas"]["Quantity"];
                memory?: components["schemas"]["Quantity"];
            };
            description?: string;
            tags?: string[];
        };
        PresetDetail: components["schemas"]["Preset"] & {
            /** @description 完整的 Helm values 或 K8s YAML（base64 或 inline） */
            manifest?: string;
            parameters?: {
                name?: string;
                type?: string;
                default?: unknown;
                description?: string;
            }[];
        };
        DeployRequest: {
            presetId: string;
            namespace: string;
            /** @description 可选，缺省按 preset 生成 */
            name?: string;
            /** @default 1 */
            replicas: number;
            scheduling?: {
                /**
                 * @default auto
                 * @enum {string}
                 */
                mode: "auto" | "manual";
                /** @description manual 模式下，指定每个副本的目标资源 */
                manualPlacement?: {
                    nodeName?: string;
                    npuSliceIds?: string[];
                }[];
                affinity?: {
                    /** @default true */
                    numa: boolean;
                    /** @default true */
                    hccs: boolean;
                };
            };
            parameters?: {
                [key: string]: unknown;
            };
        };
        DeployResponse: {
            deployId: string;
            workloadName?: string;
            namespace?: string;
            /** @enum {string} */
            status: "accepted" | "scheduling" | "running" | "failed";
            scheduledNodes?: string[];
            message?: string;
        };
        LogPage: {
            lines?: {
                /** Format: date-time */
                timestamp?: string;
                level?: string;
                container?: string;
                message?: string;
            }[];
            hasMore?: boolean;
            nextCursor?: string | null;
        };
        MetricQueryRequest: {
            /** @description 白名单模板 id */
            templateId: string;
            variables?: {
                [key: string]: string;
            };
            range?: {
                /** Format: date-time */
                start?: string;
                /** Format: date-time */
                end?: string;
                /** @example 30s */
                step?: string;
            };
        };
        MetricTemplate: {
            id?: string;
            name?: string;
            promQL?: string;
            variables?: {
                name?: string;
                required?: boolean;
                description?: string;
            }[];
        };
        MetricQueryResponse: {
            result?: {
                metric?: {
                    [key: string]: string;
                };
                values?: unknown[][];
            }[];
        };
        GrafanaURL: {
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            expiresAt?: string;
            embedToken?: string | null;
        };
        WSMessage: {
            /** @enum {string} */
            type: "topology.update" | "topology.delta" | "workload.statusChanged" | "workload.created" | "workload.deleted" | "log.line" | "metric.sample" | "error";
            /** Format: date-time */
            timestamp?: string;
            payload: components["schemas"]["Topology"] | components["schemas"]["Workload"] | {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NotFound",
                 *       "message": "资源不存在",
                 *       "details": {
                 *         "resource": "cluster",
                 *         "id": "c-xxx"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BadRequest",
                 *       "message": "参数缺失或格式错误",
                 *       "details": {
                 *         "field": "clusterId"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源冲突(已存在 / 状态冲突) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "Conflict",
                 *       "message": "部署目标 NPU 已被其他工作负载占用",
                 *       "details": {
                 *         "conflictingDeployId": "d-yyy"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "Unauthorized",
                 *       "message": "缺少有效凭证"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 已认证但无权限 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "Forbidden",
                 *       "message": "当前用户无 deploy 权限"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务器内部错误 */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "InternalError",
                 *       "message": "后端聚合上游失败",
                 *       "details": {
                 *         "upstream": "prometheus",
                 *         "reason": "timeout"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ClusterIdPath: string;
        NodeNamePath: string;
        NamespacePath: string;
        NamePath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
