//go:build !ignore_autogenerated

/*
Copyright .

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AscendClaimAnnotations) DeepCopyInto(out *AscendClaimAnnotations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AscendClaimAnnotations.
func (in *AscendClaimAnnotations) DeepCopy() *AscendClaimAnnotations {
	if in == nil {
		return nil
	}
	out := new(AscendClaimAnnotations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AscendDevice) DeepCopyInto(out *AscendDevice) {
	*out = *in
	out.SliceAICoreCapacity = in.SliceAICoreCapacity.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AscendDevice.
func (in *AscendDevice) DeepCopy() *AscendDevice {
	if in == nil {
		return nil
	}
	out := new(AscendDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceAllocation) DeepCopyInto(out *NPUSliceAllocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceAllocation.
func (in *NPUSliceAllocation) DeepCopy() *NPUSliceAllocation {
	if in == nil {
		return nil
	}
	out := new(NPUSliceAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NPUSliceAllocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceAllocationList) DeepCopyInto(out *NPUSliceAllocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NPUSliceAllocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceAllocationList.
func (in *NPUSliceAllocationList) DeepCopy() *NPUSliceAllocationList {
	if in == nil {
		return nil
	}
	out := new(NPUSliceAllocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NPUSliceAllocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceAllocationSpec) DeepCopyInto(out *NPUSliceAllocationSpec) {
	*out = *in
	out.ClaimRef = in.ClaimRef
	out.SliceRef = in.SliceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceAllocationSpec.
func (in *NPUSliceAllocationSpec) DeepCopy() *NPUSliceAllocationSpec {
	if in == nil {
		return nil
	}
	out := new(NPUSliceAllocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceAllocationStatus) DeepCopyInto(out *NPUSliceAllocationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AllocatedAt != nil {
		in, out := &in.AllocatedAt, &out.AllocatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceAllocationStatus.
func (in *NPUSliceAllocationStatus) DeepCopy() *NPUSliceAllocationStatus {
	if in == nil {
		return nil
	}
	out := new(NPUSliceAllocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceTemplate) DeepCopyInto(out *NPUSliceTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceTemplate.
func (in *NPUSliceTemplate) DeepCopy() *NPUSliceTemplate {
	if in == nil {
		return nil
	}
	out := new(NPUSliceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NPUSliceTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceTemplateList) DeepCopyInto(out *NPUSliceTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NPUSliceTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceTemplateList.
func (in *NPUSliceTemplateList) DeepCopy() *NPUSliceTemplateList {
	if in == nil {
		return nil
	}
	out := new(NPUSliceTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NPUSliceTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceTemplateSpec) DeepCopyInto(out *NPUSliceTemplateSpec) {
	*out = *in
	if in.Composition != nil {
		in, out := &in.Composition, &out.Composition
		*out = make([]TemplatePart, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceTemplateSpec.
func (in *NPUSliceTemplateSpec) DeepCopy() *NPUSliceTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(NPUSliceTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NPUSliceTemplateStatus) DeepCopyInto(out *NPUSliceTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NPUSliceTemplateStatus.
func (in *NPUSliceTemplateStatus) DeepCopy() *NPUSliceTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(NPUSliceTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceReference) DeepCopyInto(out *SliceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceReference.
func (in *SliceReference) DeepCopy() *SliceReference {
	if in == nil {
		return nil
	}
	out := new(SliceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplatePart) DeepCopyInto(out *TemplatePart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplatePart.
func (in *TemplatePart) DeepCopy() *TemplatePart {
	if in == nil {
		return nil
	}
	out := new(TemplatePart)
	in.DeepCopyInto(out)
	return out
}
